# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d72e643a4aa800a6797d3ed9ceb2c1e61c2b503dabfc02265eaacfb836a10d665c377a27dae981041703bf7e65991927b799c84f5152d10e8390a0cc5b2dd7

test:
  secret_key_base: dcd56d30eb672b3e5cea3ccd9393b6fea6312225e9268a938397680cda05d37b60dfa8cb1e4214717746ba98b34d6532b7b5d76c410b1cb671cc84c7b1ef2268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
